# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/nutritional_llm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ollama LLM Service Configuration
ollama.base-url=http://127.0.0.1:11434
ollama.timeout-seconds=1200

# Spring boot logging
logging.level.edu.utem.ftmk=INFO
logging.level.org.springframework.web=INFO
